# Generated by Django 3.2.2 on 2021-06-30 04:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0015_auto_20210630_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyapplicant',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='facultyapplicant',
            name='remarks',
            field=models.CharField(default='Submitted', max_length=25),
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 30, 22, 924507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 30, 22, 924507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 30, 22, 924507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 30, 22, 924507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 4, 30, 22, 924507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 30, 22, 924507, tzinfo=utc)),
        ),
    ]
